name: deploy

on:
  workflow_run:
    workflows: ["tests"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'}}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup ssh
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: deploy to server
      env:
        HOST_USERNAME: ${{ secrets.HOST_USERNAME }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_PATH: ${{ secrets.SERVER_PATH }}
      run: |
        rsync -avzr -e "ssh -p $SERVER_PORT" ./build/ $HOST_USERNAME@$SERVER_IP:$SERVER_PATH