name: deploy

on:
  workflow_run:
    workflows: ["tests"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Server
      env:
        HOST_PASSWORD: ${{ secrets.HOST_PASSWORD }}
        HOST_USERNAME: ${{ secrets.HOST_USERNAME }}
      run: |
        # Deployment commands go here
        scp -r ./dist user@example.com:/path/to/deploy