name: deploy

on:
  workflow_run:
    workflows: ["tests"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Server
      env:
        HOST_PASSWORD: ${{ secrets.HOST_PASSWORD }}
        HOST_USERNAME: ${{ secrets.HOST_USERNAME }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
      run: |
        scp -P $SERVER_PORT -r ./dist ${{ secrets.HOST_USERNAME }}@example.com:/path/to/deploy