name: deploy

on:
  workflow_run:
    workflows: ["tests"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'}}
    runs-on: ubuntu-latest
    
    steps:
      - name: git-checkout
        uses: actions/checkout@v4

      - name: install dependencies
        run: npm ci

      - name: build project
        run: npm run build

      - name: deploy to server
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.TOKEN_MAIN_GITHUB }}
          MESSAGE: "Build: ({sha}) {msg}"